#!/usr/bin/env python3
"""
iaas_gen.py — parse iaas-source.md, emit iaas-providers.yaml + iaas-providers.json.

Usage:
    python iaas_gen.py [--source iaas-source.md] [--out-dir .]

Output files (overwritten on each run):
    iaas-providers.yaml  — providers list in cloud_status.py format (merge into config.yaml)
    iaas-providers.json  — full structured data for cti/sources/iaas_status.py

Rules (antirez: describe the data, don't encode it):
    - Parses "## Provider: <id>" blocks with "- key: value" attributes.
    - Lines starting with "#" or empty are ignored.
    - enabled: false  →  provider emitted in JSON but omitted from YAML active list.
    - status_type: statuspage  →  YAML entry with url + page (cloud_status.py compatible).
    - status_type: html|rss    →  JSON only (no machine-readable Statuspage API).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# ── Statuspage API suffix ─────────────────────────────────────────────────────
_STATUSPAGE_SUFFIX = "/api/v2/summary.json"

# ── Type → cloud_status.py "type" field mapping ───────────────────────────────
_TYPE_MAP = {
    "statuspage": "statuspage",
    "rss":        "rss",
    "html":       "html",  # not natively supported, will be noted in output
    "gcp":        "gcp",
}

# ── YAML header (no PyYAML dep — we emit literal text, clean and readable) ───
_YAML_HEADER = """\
# iaas-providers.yaml — generated by iaas_gen.py — DO NOT EDIT BY HAND
# Source: iaas-source.md
#
# Paste the "providers" block into config.yaml under cloud_status:
#   cloud_status:
#     enabled: true
#     providers: !include iaas-providers.yaml   # or copy-paste the list below
#
# Only providers with status_type=statuspage and enabled=true are included here.
# HTML-only providers are in iaas-providers.json.

providers:
"""


def _parse_source(path: Path) -> list[dict]:
    """Parse iaas-source.md → list of provider dicts."""
    providers: list[dict] = []
    current: dict | None = None

    header_re = re.compile(r"^##\s+Provider:\s+(\S+)", re.IGNORECASE)
    attr_re    = re.compile(r"^-\s+(\w+):\s*(.*)")

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or (line.startswith("#") and not line.startswith("##")):
            continue

        m = header_re.match(line)
        if m:
            if current:
                providers.append(current)
            current = {"id": m.group(1)}
            continue

        m = attr_re.match(line)
        if m and current is not None:
            key, val = m.group(1).strip(), m.group(2).strip()
            # bool coercion
            if val.lower() == "true":
                val = True
            elif val.lower() == "false":
                val = False
            current[key] = val

    if current:
        providers.append(current)

    return providers


def _validate(p: dict) -> list[str]:
    """Return list of validation errors for provider dict."""
    errors = []
    for req in ("id", "name", "region", "status_url", "status_type", "page"):
        if not p.get(req):
            errors.append(f"missing field '{req}'")
    st = p.get("status_type", "")
    if st and st not in _TYPE_MAP:
        errors.append(f"unknown status_type '{st}' (valid: {list(_TYPE_MAP)})")
    return errors


def _to_yaml_block(p: dict) -> str:
    """Emit a single YAML provider entry (2-space indent, cloud_status.py format)."""
    url = p["status_url"].rstrip("/")
    # cloud_status.py statuspage handler appends the API suffix itself
    lines = [
        f'  - name: "{p["name"]}"',
        f'    type: {_TYPE_MAP[p["status_type"]]}',
        f'    url: "{url}"',
        f'    page: "{p["page"]}"',
        f'    region: "{p.get("region", "IT")}"',
    ]
    if p.get("notes"):
        lines.append(f'    # {p["notes"]}')
    return "\n".join(lines)


def _emit_yaml(providers: list[dict], dest: Path) -> int:
    """Write iaas-providers.yaml. Returns count of written entries."""
    active = [
        p for p in providers
        if p.get("enabled", True) and p.get("status_type") in ("statuspage", "gcp", "rss")
    ]
    blocks = [_to_yaml_block(p) for p in active]
    dest.write_text(_YAML_HEADER + "\n".join(blocks) + "\n", encoding="utf-8")
    return len(active)


def _emit_json(providers: list[dict], dest: Path) -> int:
    """Write iaas-providers.json. Returns count of written entries."""
    out = []
    for p in providers:
        entry = {
            "id":          p["id"],
            "name":        p["name"],
            "region":      p.get("region", "IT"),
            "location":    p.get("location", ""),
            "tier":        p.get("tier", ""),
            "status_url":  p["status_url"],
            "status_type": p["status_type"],
            "page":        p["page"],
            "enabled":     bool(p.get("enabled", True)),
            "notes":       p.get("notes", ""),
        }
        out.append(entry)
    dest.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    return len(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--source",  default="iaas-source.md",  help="input markdown file")
    ap.add_argument("--out-dir", default=".",                help="output directory")
    args = ap.parse_args()

    src = Path(args.source)
    out = Path(args.out_dir)

    if not src.exists():
        print(f"error: source file not found: {src}", file=sys.stderr)
        return 1

    providers = _parse_source(src)
    if not providers:
        print("error: no providers parsed — check iaas-source.md syntax", file=sys.stderr)
        return 1

    # validation
    ok = True
    for p in providers:
        errs = _validate(p)
        if errs:
            print(f"warn: provider '{p.get('id', '?')}': {'; '.join(errs)}", file=sys.stderr)
            ok = False

    yaml_dest = out / "iaas-providers.yaml"
    json_dest = out / "iaas-providers.json"

    n_yaml = _emit_yaml(providers, yaml_dest)
    n_json = _emit_json(providers, json_dest)

    print(f"parsed  : {len(providers)} providers")
    print(f"yaml out: {yaml_dest}  ({n_yaml} active statuspage entries)")
    print(f"json out: {json_dest}  ({n_json} total entries)")

    return 0 if ok else 0  # warn but don't fail on validation issues


if __name__ == "__main__":
    sys.exit(main())
